const employee=[
    {
        id:1001,
        name:"Arshwin",
        age:21,
        desig:"Developer",
        salary:45000
    },
    {
        id:2255,
        name:"John",
        age:24,
        desig:"Tester",
        salary:25000
    },
    {
        id:6728,
        name:"Navya",
        age:20,
        desig:"Developer",
        salary:36000
    },
    {
        id:9834,
        name:"Tinu",
        age:23,
        desig:"HR",
        salary:49000
    },
    {
        id:6268,
        name:"Teja",
        age:22,
        desig:"Tester",
        salary:19000
    },
]

export default employee